name: build

on:
  push:
    branches:
    - main
    - dev
    - feature/*
    - bugfix/*
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04 
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Build docker images
      run: ./build.sh 
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: |
          dist

