name: build

on:
  push:
    branches:
    - main
    - dev
    - feature/*
    - bugfix/*
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs:
      using: 'docker'
      image: 'Dockerfile'
